// export const ARTICLES_FETCH_REQUESTED = "ARTICLES_FETCH_REQUESTED";
// export const ARTICLES_FETCH_SUCCEEDED = "ARTICLES_FETCH_SUCCEEDED";
// export const ARTICLES_FETCH_FAILED = "ARTICLES_FETCH_FAILED";
// export const ARTICLES_FETCH_CLEARED = "ARTICLES_FETCH_CLEARED";

// export const ARTICLE_FETCH_REQUESTED = "ARTICLE_FETCH_REQUESTED";
// export const ARTICLE_FETCH_SUCCEEDED = "ARTICLE_FETCH_SUCCEEDED";
// export const ARTICLE_FETCH_FAILED = "ARTICLE_FETCH_FAILED";
// export const ARTICLE_FETCH_CLEARED = "ARTICLE_FETCH_CLEARED";

// export const ARTICLE_EDIT_REQUESTED = "ARTICLE_EDIT_REQUESTED";
// export const ARTICLE_EDIT_SUCCEEDED = "ARTICLE_EDIT_SUCCEEDED";
// export const ARTICLE_EDIT_FAILED = "ARTICLE_EDIT_FAILED";
// export const ARTICLE_EDIT_CLEARED = "ARTICLE_EDIT_CLEARED";

// export const ARTICLE_REMOVE_REQUESTED = "ARTICLE_REMOVE_REQUESTED";
// export const ARTICLE_REMOVE_SUCCEEDED = "ARTICLE_REMOVE_SUCCEEDED";
// export const ARTICLE_REMOVE_FAILED = "ARTICLE_REMOVE_FAILED";
// export const ARTICLE_REMOVE_CLEARED = "ARTICLE_REMOVE_CLEARED";

// export const ARTICLE_ADD_REQUESTED = "ARTICLE_ADD_REQUESTED";
// export const ARTICLE_ADD_SUCCEEDED = "ARTICLE_ADD_SUCCEEDED";
// export const ARTICLE_ADD_FAILED = "ARTICLE_ADD_FAILED";
// export const ARTICLE_ADD_CLEARED = "ARTICLE_ADD_CLEARED";
